-- ���̺� ����
DROP TABLE "CRUNCH"."USERINFO";
CREATE TABLE "CRUNCH"."USERINFO"
(
    "USERID"          NUMBER            NOT NULL ENABLE,
    "ACCOUNTID"       VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "ACCOUNTPASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "USERNAME"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "REGISTERNUMBER"  CHAR(13 BYTE)     NOT NULL ENABLE,
    "MOBILENUMBER"    VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "GENDER"          VARCHAR2(6 BYTE)  NOT NULL ENABLE,
    "EMAIL"           VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "JOINDATE"        DATE DEFAULT SYSDATE,
    "RETIREDATE"      DATE,
    "POSITIONCODE"    NUMBER,
    CONSTRAINT "USERINFO_PK" PRIMARY KEY ("USERID")
);

-- ���� (FK) ����
ALTER TABLE USERINFO
    ADD CONSTRAINT USERINFO_FK FOREIGN KEY (POSITIONCODE) REFERENCES POSITION (POSITIONCODE);
    
-- ������ ���� �� ����
DELETE
FROM USERINFO;
DROP SEQUENCE USERINFO_USERID_SEQ;
CREATE SEQUENCE USERINFO_USERID_SEQ;


-- ���̺� Ȯ��
SELECT *
FROM USERINFO;

-- ���̵����� ����
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'GEMINI', '12131415', '�����', '9101011245124', '01021132323', 'MALE',
        'KJY@NAVER.COM', 3);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'NOKENOKE', '10293847', '����', '8302131256132', '01012314231', 'FEMALE',
        'KNOCK@NAVER.COM', 4);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'JJONGGU', '12345678', '������', '5809231231212', '01021112222', 'MALE',
        'YOUNDU@NAVER.COM', 7);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'JJANGGU', '23456789', '������', '6903222849574', '01035083929', 'FEMALE',
        'MATTUIKI@NAVER.COM', 6);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'JJANGAA', '34567891', '��Â��', '8703132152123', '01078992034', 'MALE',
        'LAMBDA@NAVER.COM', 10);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'DULLY', '45678912', 'Ȫ�浿', '9503211522342', '01044013890', 'MALE',
        'JAVA@NAVER.COM', 1);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'PICOLO', '56789123', '�����', '9412311232232', '01072839281', 'MALE',
        'PYTHON@NAVER.COM', 1);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'SSAMJANG', '67891234', '�Ǳ�Ű��', '9101201231312', '01094613467', 'MALE',
        'JQUERY@NAVER.COM', 5);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'JJONDIKI', '78912345', '�˵��', '7603192211559', '01045612852', 'FEMALE',
        'JSTL@NAVER.COM', 5);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'RAMYEON', '89123456', '���Ζ��', '8304222123209', '01089077545', 'FEMALE',
        'JEONDAL@NAVER.COM', 7);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'ANIRAGO', '91234567', '�Ƴ���', '9109201250991', '01012305991', 'MALE',
        'DRAMSRAM@NAVER.COM', 8);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'KINGBAT', '13479125', 'Ŷ�޵�', '9102242215167', '01029005899', 'FEMALE',
        'QUESTION@NAVER.COM', 10);
INSERT INTO USERINFO(USERID, ACCOUNTID, ACCOUNTPASSWORD, USERNAME, REGISTERNUMBER, MOBILENUMBER, GENDER, EMAIL,
                     POSITIONCODE)
VALUES (USERINFO_USERID_SEQ.NEXTVAL, 'PUNCHCRUNCH', '75369852', 'Ũ��Ġ', '9008292214234', '01028761010', 'FEMALE',
        'RONDO@NAVER.COM', 12);

COMMIT;