DROP TABLE CRUNCH.BOARD;
CREATE TABLE CRUNCH.BOARD
(
    POSTID       NUMBER
        CONSTRAINT "BOARD_PK"
            PRIMARY KEY,
    SUBJECT      VARCHAR2(100)  NOT NULL,
    USERNAME     VARCHAR2(20)   NOT NULL,
    CONTENT      VARCHAR2(2000) NOT NULL,
    WRITEDATE    DATE        DEFAULT SYSDATE,
    UPDATEDATE   DATE,
    DELETEDATE   DATE,
    HIT          NUMBER      DEFAULT 0,
    COMMENTCOUNT NUMBER      DEFAULT 0,
    NOTICE       VARCHAR2(5) DEFAULT 'FALSE',
    IP           VARCHAR2(20),
    ATTACHLIST   VARCHAR2(1000),
    USERID       NUMBER         NOT NULL
        CONSTRAINT "BOARD_FK"
            REFERENCES CRUNCH.USERINFO
)
/

ALTER TABLE BOARD
    ADD CONSTRAINT BOARD_FK FOREIGN KEY (USERID) REFERENCES USERINFO (USERID);

COMMENT ON COLUMN CRUNCH.BOARD.POSTID IS '글 번호'
/

COMMENT ON COLUMN CRUNCH.BOARD.SUBJECT IS '글 제목'
/

COMMENT ON COLUMN CRUNCH.BOARD.USERNAME IS '성명'
/

COMMENT ON COLUMN CRUNCH.BOARD.CONTENT IS '글 내용'
/

COMMENT ON COLUMN CRUNCH.BOARD.WRITEDATE IS '작성일'
/

COMMENT ON COLUMN CRUNCH.BOARD.UPDATEDATE IS '수정일'
/

COMMENT ON COLUMN CRUNCH.BOARD.DELETEDATE IS '삭제일'
/

COMMENT ON COLUMN CRUNCH.BOARD.HIT IS '조회수'
/

COMMENT ON COLUMN CRUNCH.BOARD.COMMENTCOUNT IS '덧글 수'
/

COMMENT ON COLUMN CRUNCH.BOARD.NOTICE IS '공지글 여부'
/

COMMENT ON COLUMN CRUNCH.BOARD.IP IS 'IP 주소'
/

COMMENT ON COLUMN CRUNCH.BOARD.USERID IS '사원번호'
/

DELETE
FROM BOARD;
DROP SEQUENCE BOARD_POSTID_SEQ;
CREATE SEQUENCE BOARD_POSTID_SEQ;

SELECT *
FROM BOARD
ORDER BY POSTID DESC;
SELECT *
FROM BOARD
WHERE POSTID = 1;

INSERT INTO BOARD (POSTID, SUBJECT, USERNAME, CONTENT, NOTICE, USERID)
VALUES (BOARD_POSTID_SEQ.NEXTVAL, '1등', 'EMMA', '1등입니다!', 'FALSE', 1);
INSERT INTO BOARD (POSTID, SUBJECT, USERNAME, CONTENT, NOTICE, USERID)
VALUES (BOARD_POSTID_SEQ.NEXTVAL, '2등', 'ANBIN', '2등입니다!', 'FALSE', 2);
INSERT INTO BOARD (POSTID, SUBJECT, USERNAME, CONTENT, NOTICE, USERID)
VALUES (BOARD_POSTID_SEQ.NEXTVAL, '3등', 'TERRY', '3등입니다!', 'FALSE', 3);
INSERT INTO BOARD (POSTID, SUBJECT, USERNAME, CONTENT, NOTICE, USERID)
VALUES (BOARD_POSTID_SEQ.NEXTVAL, '4등', 'KYLE', '4등입니다!', 'FALSE', 4);

COMMIT;