DROP TABLE CRUNCH.BOARDATTACH;
CREATE TABLE CRUNCH.BOARDATTACH
(
    UUID       VARCHAR2(100)
        CONSTRAINT "BOARDATTACH_PK"
        PRIMARY KEY,
    UPLOADPATH VARCHAR2(200) NOT NULL,
    FILENAME   VARCHAR2(100) NOT NULL,
    FILETYPE   CHAR DEFAULT 'I',
    POSTID     NUMBER
        CONSTRAINT "BOARDATTACH_FK"
            REFERENCES CRUNCH.BOARD
)
    /

ALTER TABLE BOARDATTACH
    ADD CONSTRAINT BOARDATTACH_FK FOREIGN KEY (POSTID) REFERENCES BOARD (POSTID);