DROP TABLE BOARDCOMMENT;
CREATE TABLE BOARDCOMMENT
(
    COMMENTID  NUMBER
        CONSTRAINT "BOARDCOMMENT_PK"
            PRIMARY KEY,
    USERNAME   VARCHAR2(20)   NOT NULL,
    CONTENT    VARCHAR2(2000) NOT NULL,
    WRITEDATE  DATE DEFAULT SYSDATE,
    UPDATEDATE DATE,
    DELETEDATE DATE,
    IP         VARCHAR2(20),
    POSTID     NUMBER         NOT NULL,
    USERID     NUMBER         NOT NULL
)
/

ALTER TABLE BOARDCOMMENT
    ADD CONSTRAINT BOARDCOMMENT_USERINFO_FK FOREIGN KEY (USERID) REFERENCES USERINFO (USERID);

ALTER TABLE BOARDCOMMENT
    ADD CONSTRAINT BOARDCOMMENT_BOARD_FK FOREIGN KEY (POSTID) REFERENCES BOARD (POSTID);

DELETE FROM BOARDCOMMENT;
DROP SEQUENCE BOARDCOMMENT_COMMENTID_SEQ;
CREATE SEQUENCE BOARDCOMMENT_COMMENTID_SEQ;
COMMIT;

INSERT INTO BOARDCOMMENT (COMMENTID, USERNAME, CONTENT, POSTID, USERID)
VALUES (BOARDCOMMENT_COMMENTID_SEQ.NEXTVAL, 'ANONYM', '<MARQUEE>1등입니다!</MARQUEE>', 1127, 0);