DROP TABLE MEMO;
create table MEMO
(
    MEMOID     NUMBER           not null
        constraint "MEMO_pk"
            primary key,
    USERID     NUMBER
        constraint MEMO_USERID__FK
            references USERINFO,
    RECEIVERID VARCHAR2(20) not null,
    DELETED    NUMBER default 0,
    IMPORTANT  NUMBER default 0,
    WRITEDATE  DATE   default sysdate,
    MARKED     NUMBER default 0,
    SUBJECT    VARCHAR2(200) not null,
    CONTENT    VARCHAR2(2000) not null,
    ISNEW      NUMBER default 0 not null,
    ACCOUNTID  VARCHAR2(20) not null,
    SENDERid   VARCHAR2(20) not null,
    "userName" VARCHAR2(20)

) /

ALTER TABLE MEMO
    ADD CONSTRAINT MEMO_FK FOREIGN KEY (USERID) REFERENCES USERINFO (USERID);


DELETE
FROM MEMO;
DROP SEQUENCE MEMO_MEMOID_SEQ;
CREATE SEQUENCE MEMO_MEMOID_SEQ;
COMMIT;

UPDATE MEMO
SET DELETED=1,
    IMPORTANT=0,
    MARKED=0,
    ISNEW=0
WHERE MEMOID = 1;


SELECT COUNT(*)
FROM MEMO;
SELECT *
FROM (SELECT ROWNUM RNUM, AA.*
      FROM (SELECT *
            FROM MEMO
            ORDER BY MEMOID DESC) AA)
WHERE RECEIVERID = 1
  AND DELETED = 0
  AND RNUM BETWEEN 1 AND 200000000000;



SELECT *
FROM (SELECT ROWNUM RNUM, AA.*
      FROM (SELECT *
            FROM MEMO
            ORDER BY MEMOID DESC) AA)
WHERE RECEIVERID = 4
  AND DELETED = 0
  AND RNUM BETWEEN 1 AND 110;

SELECT COUNT(*)
FROM MEMO
WHERE RECEIVERID = 1
  AND ISNEW = 0;

SELECT COUNT(*)
FROM MEMO
WHERE RECEIVERID = 1
  AND ISNEW = 0;

SELECT *
FROM MEMO
WHERE RECEIVERID = 1
  AND ISNEW = 0;



SELECT R.*,
       (SELECT COUNT(MEMOID)
        FROM MEMO
        WHERE RECEIVERID = 1
          AND ISNEW = 0) COUNTINFORM
FROM (SELECT *
      FROM MEMO I
      WHERE RECEIVERID = 1 AND ISNEW = 0
      ORDER BY MEMOID DESC) R
WHERE ROWNUM = 1;


SELECT *
FROM MEMO
WHERE RECEIVERID = 1
  AND ROWNUM = 1
  AND ISNEW = 0
ORDER BY MEMOID DESC;
