DROP TABLE MEMO;
CREATE TABLE MEMO
(
    MEMOID     NUMBER           NOT NULL
        CONSTRAINT "MEMO_PK"
            PRIMARY KEY,
    USERID     NUMBER
        CONSTRAINT MEMO_USERID__FK
            REFERENCES USERINFO,
    RECEIVERID VARCHAR2(20)     NOT NULL,
    DELETED    NUMBER DEFAULT 0 ,
    IMPORTANT  NUMBER DEFAULT 0 ,
    WRITEDATE  DATE   DEFAULT SYSDATE,
    MARKED     NUMBER DEFAULT 0 ,
    SUBJECT    VARCHAR2(200)    NOT NULL,
    CONTENT    VARCHAR2(2000)   NOT NULL,
    ISNEW      NUMBER DEFAULT 0 NOT NULL,
    ACCOUNTID  VARCHAR2(20) NOT NULL ,
    "USERNAME" VARCHAR2(20)

)
    /

ALTER TABLE MEMO
    ADD CONSTRAINT MEMO_FK FOREIGN KEY (USERID) REFERENCES USERINFO (USERID);


DELETE FROM MEMO;
DROP SEQUENCE MEMO_MEMOID_SEQ;
CREATE SEQUENCE MEMO_MEMOID_SEQ;
COMMIT;

INSERT INTO MEMO(MEMOID, SUBJECT, CONTENT, USERID, "USERNAME", RECEIVERID, ACCOUNTID, DELETED, ISNEW)
VALUES (MEMO_MEMOID_SEQ.NEXTVAL, 'ㅎㅇ', 'ㅂㅇ', 1, 'ㅇㅇ', 1, '123456', 1, 1);
COMMIT;

INSERT INTO MEMO(MEMOID, SUBJECT, CONTENT, USERID, "USERNAME", RECEIVERID, ACCOUNTID, DELETED)
VALUES (MEMO_MEMOID_SEQ.NEXTVAL, 'ㅎㅇ', 'ㅂㅇ', 1, 'ㅇㅇ', 1, '123456', 0);
INSERT INTO MEMO(MEMOID, SUBJECT, CONTENT, USERID, "USERNAME", RECEIVERID, ACCOUNTID, DELETED)
VALUES (MEMO_MEMOID_SEQ.NEXTVAL, 'ㅎㅇ1', 'ㅂㅇ', 1, 'ㅇㅇ', 1, '123456', 0);
INSERT INTO MEMO(MEMOID, SUBJECT, CONTENT, USERID, "USERNAME", RECEIVERID, ACCOUNTID, DELETED)
VALUES (MEMO_MEMOID_SEQ.NEXTVAL, 'ㅎㅇ2', 'ㅂㅇ', 1, 'ㅇㅇ', 1, '123456', 0);
INSERT INTO MEMO(MEMOID, SUBJECT, CONTENT, USERID, "USERNAME", RECEIVERID, ACCOUNTID, DELETED)
VALUES (MEMO_MEMOID_SEQ.NEXTVAL, 'ㅎㅇ3', 'ㅂㅇ', 1, 'ㅇㅇ', 1, '123456', 0);
INSERT INTO MEMO(MEMOID, SUBJECT, CONTENT, USERID, "USERNAME", RECEIVERID, ACCOUNTID, DELETED)
VALUES (MEMO_MEMOID_SEQ.NEXTVAL, 'ㅎㅇ4', 'ㅂㅇ', 1, 'ㅇㅇ', 1, '123456', 0);
COMMIT;

UPDATE MEMO
SET  DELETED=1, IMPORTANT=0, MARKED=0, ISNEW=0
WHERE MEMOID =1;


SELECT COUNT(*)
FROM MEMO;
SELECT * FROM (
                  SELECT ROWNUM RNUM, AA.* FROM(
                                                   SELECT * FROM MEMO ORDER BY MEMOID DESC
                                               ) AA
              ) WHERE RECEIVERID = 1 AND DELETED=0 AND RNUM BETWEEN 1 AND 200000000000;



SELECT * FROM (
                  SELECT ROWNUM RNUM, AA.* FROM(
                                                   SELECT * FROM MEMO ORDER BY MEMOID DESC
                                               ) AA
              ) WHERE RECEIVERID = 4 AND DELETED=0 AND RNUM BETWEEN 1 AND 110;

SELECT COUNT(*)
FROM MEMO WHERE RECEIVERID = 1 AND ISNEW=0;

SELECT COUNT(*)
FROM MEMO
WHERE RECEIVERID = 1 AND ISNEW = 0;

SELECT *
FROM MEMO
WHERE RECEIVERID = 1 AND ISNEW = 0;




SELECT R.* , (SELECT COUNT(MEMOID) FROM MEMO
              WHERE RECEIVERID=1 AND ISNEW = 0 ) COUNTINFORM
FROM (SELECT  * FROM MEMO I WHERE RECEIVERID=1 AND ISNEW = 0   ORDER BY MEMOID DESC
     ) R WHERE  ROWNUM = 1;


SELECT * FROM MEMO
WHERE RECEIVERID = 1 AND ROWNUM = 1
  AND ISNEW = 0
ORDER BY MEMOID DESC;
